[4.x] PHP 8 Support
laravel/installer pull request #168
Opened 2020-10-29 14:19 UTC by driesvints

2020-10-29 19:05 UTC, GrahamCampbell requested changes

2020-10-29 19:05 UTC, GrahamCampbell commented on .github/workflows/tests.yml
> +        php: [^8.0]
carrot is a typo i assume?

2020-10-29 19:08 UTC, driesvints commented on .github/workflows/tests.yml
> +        php: [^8.0]
yep thanks

2020-10-31 06:59 UTC, nuernbergerA commented
Hey @driesvints 
#170 should fix it.

2020-10-31 09:35 UTC, driesvints commented
@taylorotwell Although that this library doesn't explicitly requires it, I've added `ext-fileinfo` to its dependencies which will allow us to catch the snag from above in the future more easily.

2020-10-31 09:37 UTC, merged

2020-10-31 12:53 UTC, crynobone commented
I don't think there is a need for that. From what I see the ubuntu inage has php installed with fileinfo by default while windows doesn't seem to have it. 

I seen this issue all all tests with Laravel 9 at the moment (when running on windows CI)

2020-10-31 15:55 UTC, driesvints commented
Okay I've removed it again. We'll see how it goes.